services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - boards-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=4gaBoards
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  db-data:
networks:
  boards-network: