apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.attachments.pvcname }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.pv.storageClass }}
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.attachments.size }}
