name: Auto Release
on:
  push:
    branches:
      - '*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.increment_version.outputs.new_tag }}
      ghcr_tag: ${{ steps.increment_version.outputs.ghcr_tag }}
      beta: ${{ steps.increment_version.outputs.beta }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest commit message
        id: latest_commit
        run: echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Get latest tag
        id: latest-tag
        run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT

      - name: Get short SHA for beta
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Sanitize branch name
        id: branch
        run: |
          safe_branch_name=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]' | tr '/' '-' | sed 's/[^a-z0-9._-]//g; s/^[.-]//')
          echo "safe_branch_name=$safe_branch_name" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment_version
        run: |
          latest_tag=${{ steps.latest-tag.outputs.tag }}
          major=$(echo $latest_tag | cut -d. -f1 | sed 's/v//')
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)
          beta_tag=""
          branch_tag=${{ steps.branch.outputs.safe_branch_name }}

          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            if [[ "${{ steps.latest_commit.outputs.message }}" == *"[MAJOR]"* ]]; then
                major=$((major + 1))
                minor=0
                patch=0
                beta=false
            elif [[ "${{ steps.latest_commit.outputs.message }}" == *"[MINOR]"* ]]; then
                minor=$((minor + 1))
                patch=0
                beta=false
            elif [[ "${{ steps.latest_commit.outputs.message }}" == *"[PATCH]"* ]]; then
                patch=$((patch + 1))
                beta=false
            else
                beta=true
                beta_tag="-${{ steps.slug.outputs.sha7 }}"
            fi
          else
            beta=true
            beta_tag="-${branch_tag}-${{ steps.slug.outputs.sha7 }}"
          fi

          new_tag="v$major.$minor.$patch"
          ghcr_tag="$major.$minor.$patch$beta_tag"

          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          echo "ghcr_tag=$ghcr_tag" >> $GITHUB_OUTPUT
          echo "beta=$beta" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-latest
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1

      - name: Update package.json version
        run: jq '.version = "'${{ needs.prepare.outputs.ghcr_tag }}'"' package.json > temp.json && mv temp.json package.json

      - name: Update .env version
        run: sed "s/REACT_APP_VERSION=.*/REACT_APP_VERSION=${{ needs.prepare.outputs.ghcr_tag }}/" client/.env > temp.env && mv temp.env client/.env

      - name: Update helm-chart app version
        run: awk '/appVersion:/ {$2="\"${{ needs.prepare.outputs.ghcr_tag }}\""} 1' helm-chart/Chart.yaml > temp.yaml && mv temp.yaml helm-chart/Chart.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tags
        id: build_tags
        run: |
          {
            echo 'tags<<EOF'

            if [[ "${{ needs.prepare.outputs.beta }}" == 'false' ]]; then
              echo 'ghcr.io/rargames/4gaboards:${{ needs.prepare.outputs.ghcr_tag }}-${{ matrix.arch }}'
              echo 'ghcr.io/rargames/4gaboards:latest-${{ matrix.arch }}'
              echo 'ghcr.io/rargames/4gaboards:beta-latest-${{ matrix.arch }}'
            else
              echo 'ghcr.io/rargames/4gaboards:beta-latest-${{ matrix.arch }}'
              echo 'ghcr.io/rargames/4gaboards:beta-${{ needs.prepare.outputs.ghcr_tag }}-${{ matrix.arch }}'
            fi

            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.build_tags.outputs.tags }}
          labels: version=${{ needs.prepare.outputs.ghcr_tag }}

  release:
    needs:
      - prepare
      - build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish stable multi-arch tags
        if: needs.prepare.outputs.beta == 'false'
        run: |
          docker buildx imagetools create \
            -t ghcr.io/rargames/4gaboards:latest \
            ghcr.io/rargames/4gaboards:latest-amd64 \
            ghcr.io/rargames/4gaboards:latest-arm64

          docker buildx imagetools create \
            -t ghcr.io/rargames/4gaboards:${{ needs.prepare.outputs.ghcr_tag }} \
            ghcr.io/rargames/4gaboards:${{ needs.prepare.outputs.ghcr_tag }}-amd64 \
            ghcr.io/rargames/4gaboards:${{ needs.prepare.outputs.ghcr_tag }}-arm64

          docker buildx imagetools create \
            -t ghcr.io/rargames/4gaboards:beta-latest \
            ghcr.io/rargames/4gaboards:beta-latest-amd64 \
            ghcr.io/rargames/4gaboards:beta-latest-arm64

      - name: Publish beta multi-arch tags
        if: needs.prepare.outputs.beta == 'true'
        run: |
          docker buildx imagetools create \
            -t ghcr.io/rargames/4gaboards:beta-latest \
            ghcr.io/rargames/4gaboards:beta-latest-amd64 \
            ghcr.io/rargames/4gaboards:beta-latest-arm64

          docker buildx imagetools create \
            -t ghcr.io/rargames/4gaboards:beta-${{ needs.prepare.outputs.ghcr_tag }} \
            ghcr.io/rargames/4gaboards:beta-${{ needs.prepare.outputs.ghcr_tag }}-amd64 \
            ghcr.io/rargames/4gaboards:beta-${{ needs.prepare.outputs.ghcr_tag }}-arm64

  final-release:
    if: needs.prepare.outputs.beta == 'false'
    needs:
      - prepare
      - release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.1

      - name: Update package.json version
        run: jq '.version = "'${{ needs.prepare.outputs.ghcr_tag }}'"' package.json > temp.json && mv temp.json package.json

      - name: Update .env version
        run: sed "s/REACT_APP_VERSION=.*/REACT_APP_VERSION=${{ needs.prepare.outputs.ghcr_tag }}/" client/.env > temp.env && mv temp.env client/.env

      - name: Update helm-chart app version
        run: awk '/appVersion:/ {$2="\"${{ needs.prepare.outputs.ghcr_tag }}\""} 1' helm-chart/Chart.yaml > temp.yaml && mv temp.yaml helm-chart/Chart.yaml

      - name: Push
        run: |
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Release ${{ needs.prepare.outputs.ghcr_tag }}"
          git push

      - name: Push-tag
        run: |
          git tag ${{ needs.prepare.outputs.new_tag }}
          git push --tags

      - name: Changelog
        uses: jaywcjlove/changelog-generator@v2.4.0
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (RARgames|dependabot\[bot\]|Renovate Bot)

      - name: Set release date
        id: release_date
        run: echo "date=$(date +'%Y_%m_%d')" >> $GITHUB_OUTPUT

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v3.0.2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          tag_name: '${{ needs.prepare.outputs.new_tag }}'
          name: '4ga Boards ${{ needs.prepare.outputs.ghcr_tag }}'
          body: |
            Changes since last release:
            ${{ steps.changelog.outputs.changelog }}

            Install this release using: `docker pull ghcr.io/rargames/4gaboards:${{ needs.prepare.outputs.ghcr_tag }}`
            View the changelog summary on the: [4ga Boards Blog](https://4gaboards.com/posts/${{ steps.release_date.outputs.date }}_4gaBoardsRelease_${{ needs.prepare.outputs.ghcr_tag }})
          draft: false
          prerelease: false

      - name: Trigger 4ga Boards homepage update
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.HOMEPAGE_4GA_BOARDS_DEPLOY_TOKEN }}
          repository: RARgames/4gaBoardsHomepage
          event-type: trigger-deploy

      - name: Trigger system notification for release
        run: |
          curl -X POST https://notifications.4gaboards.com/api/system-notifications \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_KEY_4GA_BOARDS_NOTIFICATIONS }}" \
            -d '{
              "type": "default",
              "title": "4ga Boards ${{ needs.prepare.outputs.ghcr_tag }} Released",
              "content": "Check out latest changes in our release blog: https://4gaboards.com/posts/${{ steps.release_date.outputs.date }}_4gaBoardsRelease_${{ needs.prepare.outputs.ghcr_tag }}",
              "targetUsers": "admins",
              "targetScope": "all_instances",
              "tag": "releases"
            }'
