name: E2E Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - name: Install pnpm
        run: npm install -g pnpm@11.1.2

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D wait-on

      - name: Install chromium
        working-directory: tests
        run: pnpm exec playwright install chromium

      - name: Start and wait for 4ga Boards
        run: |
          docker compose -f docker-compose-dev.yml up -d --wait
          cp server/.env.sample server/.env
          pnpm server:db:init
          nohup pnpm start > app.log 2>&1 &
          pnpm exec wait-on http://localhost:1337

      - name: Run e2e tests
        run: pnpm test:e2e
