name: E2E Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - name: Get pnpm version from package.json
        id: pnpm_version
        run: |
          version=$(jq -r '.engines.pnpm' package.json | sed 's/[^0-9.]//g')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Install pnpm
        run: npm install -g pnpm@${{ steps.pnpm_version.outputs.version }}

      - name: Install dependencies
        run: pnpm install

      - name: Install chromium
        working-directory: tests
        run: pnpm exec playwright install chromium

      - name: Prepare services
        run: |
          docker compose -f docker-compose-dev.yml up -d --wait
          cp server/.env.sample server/.env
          pnpm server:db:init

      - name: Start 4ga Boards and run tests
        run: pnpm ci:test:e2e
